#ifndef PROTOTIPOS_H_INCLUDED
#define PROTOTIPOS_H_INCLUDED

int cantidadEspacios(char *);///DEVUELVE LA CANTIDAD DE ESPACIOS QUE HAY EN LA PALABRA INGRESADA
void LimpieVector(char *);///AGREMOS UN VALOR EN TODAS LAS POSICIONES DE VECTOR
int RecorrerPalabraM(char *,char);///DEVUELVE LA CANTIDAD DE VECES QUE ESTA PRESENTE LA LETRA, ENVIADA, EN LA PALABRA
void DibujoCuadro(int ,char *);///DIBUJA LOS CUADRO DE LAS LETRAS, DEPENDIENDO DE LA CANTIDAD DE LETRAS QUE LE MANDEN.

#endif // PROTOTIPOS_H_INCLUDED
